spring:
  application:
    name:
      auth2
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
            clientSecret: 

github:
  principalName: 182207340