spring:
  application:
    name:
      spring-oauth2-example
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
            clientSecret: 

github:
  principalName: 
